[App]
Name = "ai.h2o.conifer-counter"
Version = "0.0.2"
Title = "Conifer Counter"
Description = "Counting the trees you sees"
LongDescription = "README.md"
Category = "Other"
Keywords = []

[Runtime]
Module = "src.tree_app"
